backend:
  name: nevejestvo
  repo: ParadiseSeeker/vue

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pc"
    label: "PC"
    folder: "pc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descriptrion", name: "descriptrion", widget: "string"}
      - {label: "Score", name: "score", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Processor", name: "processor", widget: "string"}
