backend:
  name: github
  repo: ParadiseSeeker/vue

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pc"
    label: "PC"
    folder: "pc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descriptrion", name: "descriptrion", widget: "string", required: false}
      - {label: "Score", name: "score", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Videocard"
        name: "videocard"
        widget: "relation"
        collection: "videocard"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
      - label: "Processor"
        name: "processor"
        widget: "relation"
        collection: "processor"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false


  - name: "videocard"
    label: "videocard"
    folder: "pc/videocard"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Manufacturer"
        name: "manufacturer"
        widget: "relation"
        collection: "manufacturer"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
      - {label: "Base Clock (MHz)", name: "baseClock", widget: "number", required: false}
      - {label: "Boost Clock (MHz)", name: "boostClock", widget: "number", required: false}
      - {label: "Memory Speed (GB/sec)", name: "memorySpeed", widget: "number", required: false}
      - {label: "Standard Memory Config (DDR)", name: "standardMemoryConfig", widget: "string", required: false}
      - {label: "Memory Bandwidth (GB/sec)", name: "memoryBandwidth", widget: "string", required: false}
      - {label: "Maximum GPU Temperature (in C)", name: "temperature", widget: "number", required: false}
      - {label: "Graphics Card Power (W)", name: "power", widget: "number", required: false}
      - {label: "WRecommended System Power (W)", name: "systemPower", widget: "number", required: false}
      - {label: "Supplementary Power Connectors (pin)", name: "powerConnectors", widget: "number", required: false}
      - {label: "Height (mm)", name: "height", widget: "number", required: false}
      - {label: "Length (mm)", name: "length", widget: "number", required: false}
      - {label: "Width (slot)", name: "width", widget: "number", required: false}
      - {label: "Maximum Digital Resolution", name: "maxResolution", widget: "string", required: false}
      - {label: "Standard Display Connectors", name: "memorySpeed", widget: "string", required: false}
      - {label: "Multi Monitor", name: "multiMonitor", widget: "boolean", default: true, required: false}
      - {label: "HDCP", name: "memorySpeed", widget: "string", required: false}
      - label: "Technology Support"
        name: "technologySupport"
        widget: "list"
        required: false
        fields:
          - {label: "Technology Support:", name: "technologySupportItem", widget: "string"}
          - {label: "Technology Support Field", name: "technologySupportItemField", widget: "string"}

  - name: "processor"
    label: "processor"
    folder: "pc/processor"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Manufacturer"
        name: "manufacturer"
        widget: "relation"
        collection: "manufacturer"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
      - {label: "Code Name", name: "codeName", widget: "string", required: false}
      - {label: "Processor Number", name: "number", widget: "string", required: false}
      - {label: "Lithography (nm)", name: "lithography", widget: "number", required: false}
      - {label: "Cores", name: "lithography", widget: "number", required: false}
      - {label: "Threads", name: "lithography", widget: "number", required: false}
      - {label: "Base Frequency (MHz)", name: "baseFrequency", widget: "number", required: false}
      - {label: "Boost Frequency (MHz)", name: "boostFrequency", widget: "number", required: false}
      - {label: "Bus Speed (GT/s)", name: "busSpeed", widget: "number", required: false}
      - {label: "TDP", name: "tdp", widget: "number", required: false}
      - {label: "Cache", name: "cache", widget: "number", required: false}
      - {label: "Max Memory Size", name: "maxRAM", widget: "string", required: false}
      - {label: "Memory Types", name: "typeRAM", widget: "string", required: false}
      - {label: "Max of Memory Channels", name: "channelsRAM", widget: "number", required: false}
      - {label: "Max Memory Bandwidth (GB/s)", name: "bandwidthRAM", widget: "number", required: false}
      - {label: "ECC Memory Supported", name: "eccRAM", widget: "boolean", default: false, required: false}
      - {label: "Processor Graphics", name: "memoryBandwidth", widget: "string", required: false}
      - {label: "Graphics Base Frequency", name: "memoryBandwidth", widget: "string", required: false}
      - {label: "Graphics Max Dynamic Frequency", name: "memoryBandwidth", widget: "string", required: false}
      - {label: "Graphics Video Max Memory", name: "memoryBandwidth", widget: "string", required: false}
      - {label: "Graphics Output", name: "memoryBandwidth", widget: "string", required: false}
      - {label: "Max Resolution", name: "memoryBandwidth", widget: "string", required: false}
      - label: "Advanced Technologies"
        name: "advancedTechnologies"
        widget: "list"
        fields:
          - {label: "Technology Support:", name: "technologySupportItem", widget: "string"}
          - {label: "Technology Support Field", name: "technologySupportItemField", widget: "string"}
        required: false


  - name: "manufacturer"
    label: "manufacturer"
    folder: "pc/manufacturer"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Logo", name: "logo", widget: "image", required: false}



