backend:
  name: github
  repo: ParadiseSeeker/vue

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pc"
    label: "PC"
    folder: "pc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descriptrion", name: "descriptrion", widget: "string"}
      - {label: "Score", name: "score", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Videocard"
        name: "videocard"
        widget: "relation"
        collection: "videocard"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        fields:
          - {label: "videocard", name: "videocard", widget: "string"}


  - name: "videocard"
    label: "videocard"
    folder: "pc/videocard"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Score", name: "score", widget: "number"}



  - name: "manufacturer"
    label: "manufacturer"
    folder: "pc/manufacturer"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Logo", name: "logo", widget: "image"}



